apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-store
spec: 
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# volumeClaimTemplates:
# - metadata:
#     name: mongodb-store
#   spec: 
#     accessModes:
#       - ReadWriteOnce
#   storageClassName: manual
#   resources:
#     requests:
#       storage: 1Gi