kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
      - name: client-pod
        image: evelynemwende/client-nginx:v2